# Generated by Django 3.0.7 on 2020-06-04 20:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200529_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=36)),
                ('city', models.CharField(max_length=36)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('pin', models.IntegerField()),
                ('image', models.ImageField(height_field=300, upload_to='profile_pics', width_field=300)),
                ('account_name', models.CharField(max_length=64)),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(choices=[('S', 'Savings'), ('C', 'Current'), ('F', 'Fixed Deposit')], max_length=1)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
