# Generated by Django 3.0.7 on 2020-06-04 22:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=core.models.generate_account_number),
        ),
    ]
