# Generated by Django 3.0.7 on 2020-06-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200604_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('N', 'Rather not say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('N', 'Rather not say')], max_length=1),
        ),
    ]
