# Generated by Django 3.0.7 on 2020-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200605_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pin',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
