# Generated by Django 3.0.7 on 2020-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200606_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
