# Generated by Django 3.0.7 on 2020-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200606_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='profile_pics', width_field=300),
        ),
    ]
